prePuller:
  enabled: false
hub:
  db:
    type: sqlite-memory
  rbac:
    enabled: true

singleuser:
  memory:
    guarantee: 1G
    limit: null
  image:
    name: zonca/ml_platform_jupyterhub
    tag: latest
  storage:
    type: none
    capacity: 10Gi
    extraVolumeMounts: []
    extraVolumes: []
    homeMountPath: /home/jovyan
    #type: dynamic
    class: rook-block
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

auth:
  type: cilogon
