prePuller:
  enabled: false
hub:
  db:
    type: sqlite-memory
  rbac:
    enabled: true

singleuser:
  memory:
    guarantee: 1G
    limit: null
  image:
    name: zonca/ml_platform_jupyterhub
    tag: latest
  storage:
    #type: none
    capacity: 10Gi
    extraVolumeMounts: [{"name":"nvidia-driver", "mountPath":"/host-libs", "readOnly":true]
    extraVolumes: [{"name":"nvidia-driver", "hostPath":{"path":"/var/lib/nvidia-docker/volumes/nvidia_driver/384.90/lib64"}}]
    homeMountPath: /home/jovyan
    type: dynamic
    class: rook-block
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

auth:
  type: cilogon
